version: "3.8"

services:
  web:
    env_file:
      - ./web/.env
    build:
      context: .
      dockerfile: ./Dockerfile.web
    volumes:
      - .:/web/app
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  worker:
    env_file:
      - ./web/.env
    build:
      context: .
      dockerfile: ./Dockerfile.worker
    volumes:
      - .:/web/app
    command: bundle exec sidekiq
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  db:
    driver: local
